---

- name: install JDK8 dependencies
  yum:
    name: "{{ rpm_repo }}/{{ item }}.rpm"
    state: present
  with_items: "{{ jdk.deps }}"

- name: install JDK8 
  yum:
    name: "{{ rpm_repo }}/{{ jdk_package }}.rpm"
    state: present


