resources:
  kafka:
    partitions: 2
    replication: "{{ groups['kafka'] | intersect(play_hosts)  | length -1 }}"
    topics:
      - topic1
  elasticsearch:
    shards: 1
    replicas: "{{ groups['elasticsearch'] | intersect(play_hosts) | length -1 }}"
    indexes:
      - index1



