install:
  type: rpm
  module: elasticsearch
  user: elasticsearch
  version: 2.3.0
  port: "{{ global.ports.elasticsearch }}"
  build: ""
  url: "{{ global.mirrors.elastic }}/elasticsearch"
  site: site-elasticsearch.sh
  cfg:
    - elasticsearch.yml
  services:
    - elasticsearch
  checks:
    port: yes

