- hosts: all
  roles:
    - network
    - oracle-jdk

- hosts: zookeeper
  roles:
    - zookeeper
  
- hosts: kafka
  roles:
    - kafka

- hosts: elasticsearch
  roles:
    - elasticsearch
  
- hosts: kibana
  roles:
    - kibana

- hosts: logstash
  roles:
    - logstash
  
- hosts: spark-master
  roles:
    - spark-master

- hosts: spark-worker
  roles:
    - spark-worker

- hosts: nifi
  roles:
    - nifi

- hosts: client
  roles:
    - client

- hosts: resources
  roles:
    - resources






  
