- hosts: all
  roles:
    - common
    - oracle-jdk
  become: true
  
- hosts: spark-master
  roles:
    - spark
  become: true

- hosts: spark-worker
  roles:
    - spark
  become: true

- hosts: nifi
  roles:
    - nifi
  become: true

- hosts: zookeeper
  roles:
    - zookeeper
  become: true
  
- hosts: kafka
  roles:
    - kafka
  become: true
  
- hosts: elasticsearch
  roles:
    - elasticsearch
  become: true
  
- hosts: kibana
  roles:
    - kibana
  become: true

- hosts: logstash
  roles:
    - logstash
  become: true
  
- hosts: sandbox
  roles:
    - spark
  become: true
    
