- name: "upload {{ package }}"
  copy:
    src: "{{ cache.local }}/{{ package }}"
    dest: "{{ cache.dest }}/{{ package }}"
    
- name: "install {{ package }}"
  yum:
    name: "{{ cache.dest }}/{{ package }}"
    state: present

